### ISSUE TITLE
Ошибка при активации плагина

### ISSUE THREAD

**Issue by Kleindberg** [livestreet/lsplugin-page#5]
Во время активации плагина последней версии возникает ошибка:

> CREATE TABLE IF NOT EXISTS `prefix_page` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `pid` int(11) unsigned DEFAULT NULL, `url` varchar(50) NOT NULL, `url_full` varchar(254) NOT NULL, `title` varchar(200) NOT NULL, `text` text NOT NULL, `date_add` datetime NOT NULL, `date_edit` datetime DEFAULT NULL, `seo_keywords` varchar(250) DEFAULT NULL, `seo_description` varchar(250) DEFAULT NULL, `active` tinyint(1) unsigned NOT NULL DEFAULT '1', `main` tinyint(1) unsigned NOT NULL DEFAULT '0', `sort` int(11) NOT NULL, `auto_br` tinyint(1) NOT NULL DEFAULT '1', PRIMARY KEY (`id`), KEY `pid` (`pid`), KEY `url_full` (`url_full`,`active`), KEY `title` (`title`), KEY `sort` (`sort`), KEY `main` (`main`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ; INSERT INTO `prefix_page` (`id`, `pid`, `url`, `url_full`, `title`, `text`, `date_add`, `date_edit`, `seo_keywords`, `seo_description`, `active`, `main`, `sort`, `auto_br`) VALUES (1, NULL, 'about', 'about', 'about', 'edit this page http://yousite/admin/', NOW(), NULL, '', '', 1, 1, 1, 1); ALTER TABLE `prefix_page` ADD `text_source` TEXT NULL DEFAULT NULL AFTER `text`;
> Fatal error: Class 'PluginPage_Update_dump.sql' not found in D:\Web\domains\press.zp.ua\framework\classes\modules\plugin_manager\PluginManager.class.php on line 558

Таблица в БД создается, но файла PluginPage_Update_dump.sql реально нет (в папке с плагином есть только dump.sql). Ругается на этот участок кода:
```
$sClass = 'Plugin' . func_camelize($sPlugin) . '_Update_' . $aFile['name'];
$oUpdate = new $sClass;
```
Пытался переименовать файл в PluginPage_Update_dump.sql - не помогло, менял участок кода - тоже самое. Установил насильно вписав его в файл plugins.dat, все работает, но не отображается в главном меню.

На стабильной версии LiveStreet 2.0.0 плагин встал, но не сохранялись редактирования в базу данных. И не было редактора markItUp в админке.

**Comment by mzhelskiy** [comment]
Да, в релизе LS 2.0 была исправлена ошибка с установкой плагинов, поэтому ставить только на релизную.
А про ошибки на 2.0 желательно подробнее

**Comment by Kleindberg** [comment]
Я установил плагин page из репозитория и скачал релизе LS 2.0 с официального сайта - все заработало. А вот если ставить плагин на master-версию LS - возникают вышеописанные ошибки.

**Comment by mzhelskiy** [comment]
Проверил на текущей master LS - все ок.
Вот здесь во фреймворке есть код https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/plugin_manager/PluginManager.class.php#L662  в нем как раз исправление, что только php файлы используются.

**Comment by Kleindberg** [comment]
Спасибо что так оперативно отреагировали! Потому что когда я качал сборку, там такого еще не было. Тему можно отметить как исправленную.
